  ### DATABASE ##########
# development:
#   adapter: mysql2
#   host: 127.0.0.1
#   username: "root"
#   password: ""
#   database: "MyChurchBible"

development:
  # adapter: postgresql
  adapter: mysql2
  host: 127.0.0.1
  username: admin
  password:
  database: Bible_Api

production:
  adapter: postgresql
  host: 127.0.0.1
  username: rails
  password: qFbs5069Ch
  database: Bible_Api
